language: rust
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
- cargo clean
- cargo build
- cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo clean
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch coveralls-test
    cargo tarpaulin --coveralls $TRAVIS_JOB_ID
  fi
